### ISSUE TITLE
Replace the requirement pywin32

### ISSUE THREAD

**Issue by e-nouri** [may-day/kerberos-sspi#2]
Pywin32 is not available though pip, and it is only installable through an .exe file, meanwhile, there is a wheel package created originally for Twisted called pypiwin32, can you please replace the requirement pywin32 with pypiwin32, so the hole process can be automated.

pypiwin32 seems working fin with my Kerberos setup under windows
Cheers,

**Comment by may-day** [comment]
it now depends on pypiwin32, thank you.
