### ISSUE TITLE
Mismatch between kerberos-sspi and pykerberos module for authGSSServerUserName

### ISSUE THREAD

**Issue by schlenk** [may-day/kerberos-sspi#4]
Having a Linux / Windows cross platform app which uses kerberos-sspi for the Windows side and pykerberos for the Linux side, I see a major difference when authenticating against an AD Server.

On Windows, `krb5.authGSSServerUserName()` returns a value like:

```
NTSERVER\msc
```

on Linux it is:

```
msc@NTSERVER
```

This obviously is a problem when using kerberos-sspi as a drop-in replacement for pykerberos on Windows.  In both cases it is 'NT Domain Name' + 'sAMAccountName', but combined in different ways. As one usually is after this name to know who the user really is, this is unfortunate, as it forces special handling for windows/linux again.

So depending on how you define the claimed 'API level equivalent' API, this is either a bug or a surprising feature.

**Comment by behackett** [comment]
kerberos-sspi isn't formatting the username that way. That's the format returned by [QueryContextAttributes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379328%28v=vs.85%29.aspx). It's returning the name as SSPI defines it.

**Comment by schlenk** [comment]
Yes. I know the Windows API does that. The question is what the 'API level equivalent' statement means.
1. The functions have the same names and argument order, but return wildly different values depending on the platform used.
2. The functions have the same names and argument order and return results that are the same so they can be used as drop in replacements in a cross platform way.

With 1. style API, if i have two components, one on Linux one one Windows and have the same user authenticated to both at the same time, i cannot simply compare the usernames to identify the user. I have to parse and manipulate the names to be able to compare them.
